### ISSUE TITLE
1.4 Static Functions - The Nature of Code

### ISSUE THREAD

**Issue by PiIsFour** [PiIsFour/const-methods#1]
@shiffman

Hi in your last video about Static Functions you mention that by the nature of an instance method it changes the object. Sorry but I have to disagree.

First of all, yes this is how p5 does it. But that is a design decision and not by the nature of methods.

This repo is just to show the problem with this and possible solution to it.

But don't you think it is pretty misleading to tell beginners the nature of methods is to change the object. There is a reason why people use libraries like immutable.js

Sorry if that is not a conventional method to contact you, but the video is not listed jet.

thanks for inspiring people to learn programming

**Comment by shiffman** [comment]
Hey! Thank you for the comment / feedback. Can you link me to the timecode in the video where there is an error in what I stated. I will take a look!

**Comment by PiIsFour** [comment]
https://youtu.be/YN8Q-QEmQ8Y?list=PLRqwX-V7Uu6ZV4yEcW3uDwOgGXKUUsPOM&t=409

Sure. Thanks for taking the time to look at this.

**Comment by PiIsFour** [comment]
Good this seems to be settled.
